### ISSUE TITLE
origanything?

### ISSUE THREAD

**Issue by carbeck** [semprag/biblatex-sp-unified#11]
The documentation doesn't say anything on republished works, but I still wonder if it wouldn't be good to somehow be able to include this information as well – question is how, if you want to stay true to the original style guide. I think it would at least be helpful to be able to indicate the original publication date/year of a republished work by providing support for the `origdate` and `origyear` fields, respectively.

**Comment by fintelkai** [comment]
Thanks for this issue. I will ponder. (I'm going to be away on vacation for ten days, but I wanted to comment so that you don't think you're being ignored.)

**Comment by fintelkai** [comment]
Getting back to this: do you have a suggestion of how the original year should be displayed?

**Comment by carbeck** [comment]
I suppose a very straightforward way could be to use brackets after the publishing year of the reprint.

**Comment by chbrown** [comment]
At [*S&P*](http://semprag.org/), we use the `note` field for this purpose, with values like `{Original work published 1953}` or `{Republished 1966}`.

I agree that supporting the standard BibLaTeX `origdate` and `origyear` fields would be nice, but since there is no specification for how to format these in the _Unified style sheet for linguistics_, I'm closing this.

I'd recommend starting a discussion for how to handle these at https://github.com/lx-unified-v2/lx-unified-v2, and if a solution is settled upon there, would be happy to accept a PR backporting the implementation to `biblatex-sp-unified`.
