### ISSUE TITLE
Interaction between language and title capitalization

### ISSUE THREAD

**Issue by schar** [semprag/biblatex-sp-unified#3]
I have the following entry in my `.bib` file: 

```
@article{Stechow:1996,
    Author = {von Stechow, Arnim},
    Doi = {10.1007/BF00263537},
    Issn = {0925-854X},
    Journal = {Natural Language Semantics},
    Number = {1},
    Pages = {57-110},
    Publisher = {Kluwer Academic Publishers},
    Title = {Against {LF} Pied-Piping},
    Volume = {4},
    Year = {1996}}
```

This typesets just fine using the S&P-recommended `biblatex` setup -- specifically, the title is capitalized `Against LF pied-piping`. However, if I add `Language = {English}` as a field, the title is output as `Against LF Pied-Piping`. 

In my `.sty` file, I use the following to prevent a citation's language from being printed in the bibliography:

```
\DeclareSourcemap{%use lang field for hyphenation, not printing!
  \maps{%
    \map{%
      \step[fieldsource=language, fieldset=langid, origfieldval, final]
      \step[fieldset=language, null]
    }
  }
}
```

If I get rid of these lines, the capitalization issue disappears, but the typeset bibliography entry includes `English`. 

I don't normally add language info when inputting new entries, but the `.bib` files generated by publishers often include it. Nothing urgent here, just something I thought you all might wish to be aware of.

**Comment by adamliter** [comment]
This happens because of line [248 in `biblatex-sp-unified.bbx`](https://github.com/semprag/biblatex-sp-unified/blob/master/biblatex-sp-unified.bbx#L248).

It says:

``` tex
\DeclareFieldFormat[article,book,thesis,incollection,unpublished,inproceedings]{titlecase}{\MakeSentenceCase*{#1}}%
```

If you read the description of `\MakeSentenceCase*` on p. 193 of the [`biblatex` manual](http://texdoc.net/texmf-dist/doc/latex/biblatex/biblatex.pdf) it says:

> The starred variant differs from the regular version in that it considers the language of the entry, as specified in the `langid` field. It only converts the ⟨_text_⟩ to sentence case if the `langid` field is undefined or if it holds a language declared with `\DeclareCaseLangs` (see below). [...] By default, converting to sentence case is enabled for the following language identifiers: `american`, `british`, `canadian`, `english`, `australian`, `newzealand` as well as the aliases `USenglish` and `UKenglish`. Use `\DeclareCaseLangs` to extend or change this list.

Your call to `\DeclareSourceMap` sets the `langid` field to `English`. Note that `English`=/=`english`.

Consider the following MWE. I've added (English) and (english) to the journal name just to differentiate things.

``` tex
% arara: pdflatex
% arara: biber
% arara: pdflatex
\begin{filecontents*}{\jobname.bib}
@article{Stechow:English,
    Author = {von Stechow, Arnim},
    Doi = {10.1007/BF00263537},
    Issn = {0925-854X},
    Journal = {Natural Language Semantics (English)},
    Language = {English},
    Number = {1},
    Pages = {57-110},
    Publisher = {Kluwer Academic Publishers},
    Title = {Against {LF} Pied-Piping},
    Volume = {4},
    Year = {1996}}
@article{Stechow:english,
    Author = {von Stechow, Arnim},
    Doi = {10.1007/BF00263537},
    Issn = {0925-854X},
    Journal = {Natural Language Semantics (english)},
    Language = {english},
    Number = {1},
    Pages = {57-110},
    Publisher = {Kluwer Academic Publishers},
    Title = {Against {LF} Pied-Piping},
    Volume = {4},
    Year = {1996}}
\end{filecontents*}

\documentclass{article}

\usepackage[
    backend=biber,
    bibstyle=biblatex-sp-unified,
    citestyle=sp-authoryear-comp,
    maxcitenames=3,
    maxbibnames=99
]{biblatex}

\DeclareSourcemap{%use lang field for hyphenation, not printing!
  \maps{%
    \map{%
      \step[fieldsource=language, fieldset=langid, origfieldval, final]
      \step[fieldset=language, null]
    }
  }
}

\addbibresource{\jobname.bib}

\usepackage{hyperref}
\newcommand{\doi}[1]{\textsc{doi}: \href{http://dx.doi.org/#1}{\nolinkurl{#1}}}

\begin{document}

\nocite{*}

\printbibliography

\end{document}
```

This produces:
<img width="443" alt="screen shot 2015-07-27 at 1 10 27 pm" src="https://cloud.githubusercontent.com/assets/4974404/8913804/f21f405a-3460-11e5-8a83-a08dc5dc2f0f.png">

The `biblatex` manual says that using `\MakeSentenceCase*` is best practice, so I think the current implementation of `biblatex-sp-unified.bbx` is probably the best.

(As a side note, it's not recommended to use `english` as an identifier in the `langid` field. Instead, you should use either `american` or `british` or `australian`, etc..)

Anyway, all that being said, the Unified Style Sheet for Linguistics Journals never calls for printing the language of a work in the citation, so perhaps lines [276](https://github.com/semprag/biblatex-sp-unified/blob/master/biblatex-sp-unified.bbx#L276) and [277](https://github.com/semprag/biblatex-sp-unified/blob/master/biblatex-sp-unified.bbx#L277) of `biblatex-sp-unified.bbx` could be deleted.

**Comment by adamliter** [comment]
After investigating this a bit further, this really seems like it's bad practice on the part of the publishers that are doing this. Capitalization should _not_ be used in the `language` entry field. The language will be correctly capitalized when it is typeset by `biblatex`.

@schar If you omit your `\DeclareSourcemap` in the MWE that I gave above and add `clearlang=false` to the `biblatex` options, then you will see that both `language` fields are printed as "English", with a capital 'E'.

By default, `biblatex` sets `clearlang` to `true`, which will clear the `language` entry field just in case it matches the language of the document (the idea being that redundant information can be omitted).

If you wanted to use `.bib` entries from these publishers, I suppose you could add `\DeclareRedundantLanguages{English}{english}` to your `.tex` file, which might be a better option than your current `\DeclareSourcemap` workaround.

But really the best solution would seem to be to use lowercase in the `language` field (and also to not use `english` but instead one of the more specific options like `american` or `british` or `newzealand`, as the `biblatex` documentation recommends).

**Comment by schar** [comment]
Thanks, @adamliter. This is helpful. I agree that this seems like the publishers' mistake -- assuming the `english`/`English` thing isn't a peculiarity of `biblatex`. 

I'll leave this open a little longer, in case @fintelkai or someone else wishes to weigh in.

**Comment by adamliter** [comment]
@schar No problem! And I'm not sure that I honestly understand what you mean when you say "assuming the `english`/`English` thing isn't a peculiarity of `biblatex`". The `language` and `langid` fields are only available with `biblatex`, not BibTeX, so this is a thing that is indeed specific to `biblatex.`

But the preference for lowercase is for a very good reason—namely, since `biblatex` relies on the packages `babel` and `polyglossia` for language specific typesetting, it follows the practice of those two packages in using lowercase names for languages.

Anyway, I agree that it would be good to see if @fintelkai has thoughts on this.

**Comment by fintelkai** [comment]
Seems like the two of you came to a good conclusion. Nothing for biblatex-sp-unified to do here. Closing the issue. Thanks!
