### ISSUE TITLE
LingBuzz eprint support

### ISSUE THREAD

**Issue by alecshaw** [semprag/biblatex-sp-unified#30]
Hello, I have implemented support for the `eprint` and `eprinttype` for the LingBuzz (http://ling.auf.net/lingbuzz) repository.

I think it's cleaner than having a whole URL.

![lingbuzz-eprint](https://cloud.githubusercontent.com/assets/10132281/23904406/a6abb04c-08bf-11e7-8063-984030ef2e67.png)

I'm wondering what everyone thinks of this, and whether a pull request would be accepted.

If so, then I intend to also include support for the Rutgers Optimality Archive (http://roa.rutgers.edu/).

**Comment by fintelkai** [comment]
@alecshaw Please do propose the code. We have to update the display of DOIs anyway (new guidelines say to use "https://doi.org/..." instead of "http://dx.doi.org/...". So, revisiting the URL displays in general makes sense. I'm thinking we might want an option that controls whether full URLs are displayed or short versions like yours (and similarly for DOIs).

**Comment by alecshaw** [comment]
Alright. I can also go ahead and implement that fix to the DOI URL, if that's fine with you.

**Comment by fintelkai** [comment]
Thanks for the PRs. We will cherry-pick the changes and wrap them so as to allow the users to choose whether to display full URLs or the shortened versions. Stay tuned.
