### ISSUE TITLE
Upcoming changes in biblatex 3.8

### ISSUE THREAD

**Issue by moewew** [semprag/biblatex-sp-unified#38]
`biblatex` 3.8 is scheduled for release quite soon.

At least one of the changes is relevant for your style.
- `extrayear` is going to be renamed to `extradate`, and all macros names making reference to that field are also going to be changed.
The old names should continue to work, but will issue warnings, so it would be appreciated if styles were to use the new names sooner rather than later.

You can find the full list of changes at https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org and https://github.com/plk/biblatex/wiki

**Comment by fintelkai** [comment]
Thanks for the heads up, @moewew !

**Comment by fintelkai** [comment]
Thanks, @alecshaw. Is this backwards-compatible or will older version of biblatex croak now? Compare https://github.com/semprag/biblatex-sp-unified/pull/27 for how we added some guards for a previous change. This is perhaps moot now? I really don't know for how many versions of biblatex, we should add conditionals.

**Comment by alecshaw** [comment]
Right, that hadn't occurred to me. Sorry about that. Likely croaking in older versions. I'll look into a conditional like #27 to maintain backward compatibility. I think given that the deprecation is just one version out, I think a conditional makes sense here.

I like to have the latest updates for things, but I know a few users never update their LaTeX installations. Any thoughts from the community about how many versions of biblatex to support?

**Comment by chbrown** [comment]
I merged #39 as-is, and added a section about supporting older biblatex versions (via tags) to the README: https://github.com/semprag/biblatex-sp-unified#backward-compatibility

My reasoning:
* Since `biblatex-sp-unified` is not (currently) published to CTAN, it's installed from source, in which case it's pretty easy to switch out `master` with a tag (like `3.6.0`) in the URLs.
* Versioning is kind of a mess in the TeX ecosystem (it's a mess everywhere, but moreso for TeX), and it seems the standard practice is to assume that only the latest versions of everything are guaranteed(-ish) to work nicely together.
* Backward compatibility hacks like #27 should be the responsibility of biblatex, upstream.
