### ISSUE TITLE
Problems with recognizing \begin{document} when trying to use this

### ISSUE THREAD

**Issue by ghost** [semprag/biblatex-sp-unified#41]
Hello,

i have tried to use your biblatex-sp-unified.bbx file in my document.  While trying to typeset it, the following error occured:
```
("C:\Program Files\MiKTeX 2.9\tex\latex\biblatex\bbx\biblatex-sp-unified.bbx"

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7 <
     !DOCTYPE html>
? 
```

As you can see, i am using Miktex 2.9 on Windows and tried to follow your instructions. After saving the bbx file into  biblatex\bbx and  and the cbx file into biblatex\cbx ,  i ran  "miktex option" and executed "Refresh FNDB". 
The error i mentioned does not occur when i use `\usepackage[backend=biber]{biblatex}` instead of
 ``` 
\usepackage[backend=biber,
            bibstyle=biblatex-sp-unified,
            citestyle=sp-authoryear-comp,
           maxcitenames=3,
            maxbibnames=99]{biblatex}
```

I have not seen this error mentioned anywhere else, so i am writing to you.

Any help would be much appreciated!

**Comment by fintelkai** [comment]
My guess is that you didn't actually save the two textfiles with extensions bbx and cbx. Rather you saved the html source of the github pages displaying those files. That's why LaTeX hiccups with the error message that displays `<!DOCTYPE html>`. Go to the two files on github, in each case click on "Raw" and then save the plain text file that is displayed.
