### ISSUE TITLE
Please also add unified.bst

### ISSUE THREAD

**Issue by fcbond** [semprag/biblatex-sp-unified#53]
Hi,

for those of us still using bibtex, it would be nice if you could also distribute ``.

I attach a slightly improved version, renamed to unified.txt to make github happy.
[unified.txt](https://github.com/semprag/biblatex-sp-unified/files/9946682/unified.txt)

Yours,

**Comment by fintelkai** [comment]
For legacy bibtex users, we distribute `sp.bst` (our old version of `unified.bst`) at https://github.com/semprag/tex/blob/master/sp.bst, as part of S&P's LaTeX package. It is not part of `biblatex-unified`, since that's a biblatex implementation of the Unified Stylesheet. The `biblatex-unified` readme currently has an incorrect link, which will be fixed.

If you want to maintain and distribute `unified.bst`, you're welcome to do so (on Github and/or CTAN), especially since there doesn't seem to be a reliable source for it on the internet, including CTAN.
